services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: surveillance
      POSTGRES_USER: mayssa
      POSTGRES_PASSWORD: mayssa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: