# Generated by Django 4.2.23 on 2025-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lieu_delete_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
