# Generated by Django 4.2.23 on 2025-06-27 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("creer_groupes", "Peut créer des groupes d'agents"),
                    ("gerer_secteurs", "Peut gérer les secteurs Leaflet"),
                    ("lier_cameras", "Peut associer des caméras aux secteurs"),
                    ("affecter_agents", "Peut affecter des agents aux secteurs"),
                ]
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("coordonnees", models.TextField()),
                (
                    "superviseur",
                    models.ForeignKey(
                        limit_choices_to={"role": "SUPER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupeAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "agents",
                    models.ManyToManyField(
                        limit_choices_to={"role": "AGENT"}, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groupes_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentification.secteur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=50, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "secteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentification.secteur",
                    ),
                ),
            ],
        ),
    ]
