# Generated by Django 5.2.3 on 2025-07-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
        ('gismap', '0002_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lieu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gismap.lieu', verbose_name="Secteur d'affectation"),
        ),
    ]
