# Generated by Django 4.2.23 on 2025-07-06 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gismap", "0003_camera_hls_url"),
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lieu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gismap.lieu",
                verbose_name="Secteur d'affectation",
            ),
        ),
    ]
