# Generated by Django 4.2.23 on 2025-06-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentification",
            "0002_alter_user_options_secteur_notification_groupeagent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("SUPER", "Superviseur"),
                    ("AGENT", "Agent"),
                ],
                default="AGENT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
