# Generated by Django 4.2.23 on 2025-06-28 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0003_alter_user_role_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupeagent",
            name="agents",
        ),
        migrations.RemoveField(
            model_name="groupeagent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="groupeagent",
            name="secteur",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="secteur",
            name="superviseur",
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.DeleteModel(
            name="Camera",
        ),
        migrations.DeleteModel(
            name="GroupeAgent",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Secteur",
        ),
    ]
