# Generated by Django 5.2.5 on 2025-08-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='image',
        ),
        migrations.AddField(
            model_name='notifications',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='image_type',
            field=models.CharField(blank=True, default='jpeg', max_length=10),
        ),
    ]
