# Generated by Django 5.2.4 on 2025-08-02 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionMatricule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('date_detection', models.DateField(default=django.utils.timezone.now)),
                ('heure_detection', models.TimeField(default=django.utils.timezone.now)),
                ('est_autorise', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='gismap.camera')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculeAutorise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matricules_autorises', to='gismap.lieu')),
            ],
        ),
    ]
