# Generated by Django 5.2.4 on 2025-08-04 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismap', '0002_detectionmatricule_matriculeautorise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionmatricule',
            name='date_detection',
        ),
        migrations.RemoveField(
            model_name='detectionmatricule',
            name='heure_detection',
        ),
        migrations.AddField(
            model_name='detectionmatricule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matricules/'),
        ),
        migrations.AddField(
            model_name='detectionmatricule',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='detectionmatricule',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gismap.camera'),
        ),
        migrations.AlterField(
            model_name='detectionmatricule',
            name='numero',
            field=models.CharField(max_length=255),
        ),
    ]
