# Generated by Django 4.2.23 on 2025-07-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gismap", "0002_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="hls_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
