# Generated by Django 5.2.4 on 2025-08-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gismap', '0003_remove_detectionmatricule_date_detection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='detectionmatricule',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
