# Generated by Django 4.2.23 on 2025-07-06 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gismap", "0003_camera_hls_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="hls_url",
        ),
    ]
